### ISSUE TITLE
Permissions too strict

### ISSUE THREAD

**Issue by ghost** [SpaceClouds42/PlaytimeTracker#2]
This mod is on the server(Kotlin is also there, yes: fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar)
Using the newest release of PlayTime Tracker: [https://github.com/SpaceClouds42/PlaytimeTracker/releases/tag/v0.1.0](https://github.com/SpaceClouds42/PlaytimeTracker/releases/tag/v0.1.0)
The `/playtime` command doesn't exist. The mod is definitely loaded and no errors on the console.

**Comment by spaceclouds42** [comment]
Not a bug. `/playtime` requires parameters. For more info on all of the commands, run `/playtime help`

**Comment by ghost** [comment]
Oh, but only ops(level 4) can do it.
Is that intentional?
I believe that as it works from the console but the players in-game can't do it.

**Comment by spaceclouds42** [comment]
It's supposed to be op level 4 because the commands allow you to edit/reset playtime. However, i could edit the permissions so that players can see their own and others' playtime

**Comment by ghost** [comment]
Sorry for the late response.
That would be great if it isn't too much hassle for you.

**Comment by spaceclouds42** [comment]
Oh, I'm updating Playtime Tracker and I realized that I already implemented this.
