### ISSUE TITLE
Custom advancement support for playtime criteria

### ISSUE THREAD

**Issue by James103** [SpaceClouds42/PlaytimeTracker#4]
Currently, the `playtime_tracker:playtime` advancement criteria is hardcoded to only work for the advancements that the mod adds for the specific time values that each advancement requires. I would like it if there was a way to make custom advancements using the `playtime_tracker:playtime` criteria.

As an example, suppose that you are running a server with an auction house or similar player vs player trading features. To reduce the impact of bad actors, you could require all players to have 5 hours of non-AFK playtime before they can use these features. This can be done via a custom advancement that uses the `playtime_tracker:playtime` criteria and a value (playtime requirement) of 5 hours or 360,000 ticks.

Another example would be to reward players for achieving 1 Minecraft year (365 MC days or 121 2/3 hours) of playtime. This could also be done via a custom advancement, again with the `playtime_tracker:playtime` criteria a value (playtime requirement) of 8,760,000 ticks.

The criteria name would be `playtime_tracker:playtime`, and the criteria would have several parameters for each of the different units of time, mainly the following:
* `minecraft_days` (20 minutes each)
* `days` (24 hours each)
* `hours` (1 hour each)
* `minutes` (1 minute each)
* `seconds` (1 second each)
* `milliseconds` (1 millisecond each)

At least one of these parameters (units of time) is required. If multiple units of time are specified, all of the time values specified are summed up and the advancement would be given upon reaching the total time requirement.

**Comment by spaceclouds42** [comment]
This sounds like a great idea, I'll try to work on it this week. Were you thinking of simply adding an advancement file like this?
```json
{
  "display": {
    "icon": {
      "item": "minecraft:clock"
    },
    "title": "One Hour Advancement",
    "description": "You have played for one hour",
  },
  "criteria": {
    "requirement": {
      "trigger": "playtime_tracker:playtime",
      "conditions": {
        "hours": 1
      }
    }
  }
}
```

**Comment by James103** [comment]
Something like this could work, with the unit of "hours" you proposed for simplicity, though I would like the ability to specify decimals for greater precision using a TAG_Double data type. For example, an advancement that triggers once you have played for an amount of time equivalent to the current Minecraft RSG [speedrun](https://www.speedrun.com/mc) world record of 9m 36.933s would look something like this:
```json
{
  "display": {
    "icon": {
      "item": "minecraft:iron_ingot"
    },
    "title": "Past the World Record",
    "description": "You have played longer than the current world record!",
  },
  "criteria": {
    "requirement": {
      "trigger": "playtime_tracker:playtime",
      "conditions": {
        "hours": 0.1602591666666666
      }
    }
  }
}
```
Note: `hours` is calculated as `(9 * 60 + 36.933) / 3600 = 0.1602591666...

**Comment by spaceclouds42** [comment]
oh should have given a better example. I was thinking of using multiple condition fields for more specific times.
It would have a `minecraft_days`, `days`, `hours`, `minutes`, `seconds`, and `milliseconds` fields. The advancement would be triggered once the total time has been reached
```json
"conditions": {
  "minutes": 9,
  "seconds": 36.933
}
```

**Comment by James103** [comment]
An advancement with the following for "conditions" would trigger after you have played for 25 hours, 21 minutes, and 1.501 seconds:
```json
"conditions": {
  "minecraft_days": 1,
  "days": 1,
  "hours": 1,
  "minutes": 1,
  "seconds": 1.5,
  "milliseconds": 1,
}
```
Calculation:
```
Units          | Amount | Total Time
-------------- | ------ | ---------------
minecraft_days | 1      |     20m 00.000s
days           | 1      | 24h 00m 00.000s
hours          | 1      |  1h 00m 00.000s
minutes        | 1      |      1m 00.000s
seconds        | 1.5    |          1.500s
milliseconds   | 1      |           .001s
Total          |        | 25h 21m  1.501s
```

**Comment by spaceclouds42** [comment]
Thanks a lot for this suggestion. It has been implemented in a [new api](https://github.com/SpaceServe/spaceserve-playtime) I made, and I am in the process of updating Playtime Tracker to use said api. I settled on this for the advancement format:
```
"criteria": {
    "fifty_hours": {
      "trigger": "spaceserve:playtime",
      "conditions": {
        "playtime": {
          "time": {
            "hours": 50
          },
          "afk": false
        }
      }
    }
  }
```
The full range of properties it accepts:
```json5
"criteria": {
    "fifty_hours": {
      "trigger": "spaceserve:playtime",
      "conditions": {
        "playtime": {
          // be sure to put this time block after the playtime block
          "time": {
            "days": 3,
            "hours": 1.5, // decimals work, except for milliseconds where it will be rounded off
            "minecraftDays": 3, // 1 mcday = 20 minutes
            "minutes": 2,
            "seconds": 9,
            "milliseconds": 3904
          },

          // this means that the playtime was not spent afk. if this property is undefined, it considers all playtime. can also be set to
          // true so that it only considers time spent afk
          "afk": false,

          // this means that the playtime must take place in the end or nether dimension
          // custom dimensions (should) also work
          "dimensions": ["minecraft:the_end", "minecraft:the_nether"] 
        }
      }
    }
  }
```

last example: the one you originally showed, using this new system
```json5
{
  "display": {
    "icon": {
      "item": "minecraft:iron_ingot"
    },
    "title": "Past the World Record",
    "description": "You have played longer than the current world record!",
  },
  "criteria": {
    "requirement": {
      "trigger": "spaceserve:playtime",
      "conditions": {
        "playtime": {
          "time": {
            "hours": 0.1602591666666666
          }
          // I did not define afk so that it considers all time, regardless of afk or not, but you can easily change that :)
        }
      }
    }
  }
}
```
